---
- name: Import Signing Key | ~chris-lea
  apt_key:
    state: present
    keyserver: 'hkp://keyserver.ubuntu.com:80'
    id: '0xb9316a7bc7917b12'

- name: Import Repository | ~chris-lea/redis-server
  apt_repository:
    state: present
    repo: 'deb http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty main'
  notify: Update Package Cache

- name: Trigger All Callbacks
  meta: flush_handlers

- name: Install Packages | apt | redis-tools
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - redis-tools
  when: redis_client

- name: Install Packages | apt | redis-server
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - redis-server
  when: redis_server

- name: Link Exists | /usr/local/bin/redis-sentinel
  file:
    state: link
    src: /usr/bin/redis-server
    dest: /usr/local/bin/redis-sentinel
  when: redis_sentinel_enabled
