---
- name: "Directory Exists | {{ redis_log_root }}"
  file:
    state: directory
    path: "{{ redis_log_root }}"
    owner: "{{ redis_user }}"
    group: wcadmin
    mode: 0775
  tags:
    - directory-structure
    - logging
    - redis

- name: Configure | redis-server | logfile
  lineinfile:
    state: present
    dest: /etc/redis/redis.conf
    regexp: '^#* *logfile '
    line: "logfile {{ redis_server_log_path }}"
  notify: Reload Service | redis-server
  tags:
    - configuration
    - precise-configuration
    - logging
    - redis

- name: Upload Config | beaver | redis-server
  template:
    src: etc/beaver/conf.d/redis-server
    dest: /etc/beaver/conf.d/redis-server
  tags:
    - configuration
    - template-configuration
    - logging
    - using-beaver
    - redis
