---
- name: "Directory Exists | {{ redis_log_root }}"
  file:
    state: directory
    path: "{{ redis_log_root }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    mode: 0775
  tags:
    - directory-structure
    - logging
    - redis

- name: "Correct Permissions | {{ redis_server_log_path }}"
  file:
    state: touch
    path: "{{ redis_server_log_path }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    mode: 0664
  tags:
    - permissions
    - logging
    - redis

- name: "Correct Permissions | {{ redis_sentinel_log_path }}"
  file:
    state: touch
    path: "{{ redis_sentinel_log_path }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    mode: 0664
  tags:
    - permissions
    - logging
    - redis-sentinel
  when: redis_sentinel_enabled

- name: Configure | redis-server | logfile
  lineinfile:
    state: present
    dest: /etc/redis/redis.conf
    regexp: '^#* *logfile '
    line: "logfile {{ redis_server_log_path }}"
  notify: Reload Service | redis-server
  tags:
    - configuration
    - precise-configuration
    - logging
    - redis

- name: Configure | redis-sentinel | logfile
  lineinfile:
    state: present
    dest: /etc/redis/redis-sentinel.conf
    line: "logfile {{ redis_sentinel_log_path }}"
    insertafter: EOF
  notify: Reload Service | redis-sentinel
  tags:
    - configuration
    - precise-configuration
    - logging
    - redis-sentinel
  when: redis_sentinel_enabled
