---
- name: "Directory Exists | {{ redis_runtime_root }}"
  file:
    state: directory
    path: "{{ redis_runtime_root }}"
    owner: "{{ redis_user }}"
    group: wcadmin
    mode: 0775
  tags:
    - directory-structure
    - runtime-data
    - redis

- name: Configure | redis-server | pidfile
  lineinfile:
    state: present
    dest: /etc/redis/redis.conf
    regexp: '^#* *pidfile '
    line: "pidfile {{ redis_server_pidfile_path }}"
  notify: Reload Service | redis-server

- name: Configure | redis-sentinel | pidfile
  lineinfile:
    state: present
    dest: /etc/redis/redis-sentinel.conf
    line: "pidfile {{ redis_sentinel_pidfile_path }}"
    insertafter: EOF
  notify: Reload Service | redis-sentinel
  when: redis_sentinel_enabled
