---
- name: "Directory Exists | {{ redis_runtime_root }}"
  file:
    state: directory
    path: "{{ redis_runtime_root }}"
    owner: "{{ redis_user }}"
    group: wcadmin
    mode: 0775
  tags:
    - directory-structure
    - runtime-data
    - redis

- name: Upload Config | monit | redis-server
  template:
    src: etc/monit/conf.d/redis-server
    dest: /etc/monit/conf.d/redis-server
  notify: Reload Service | monit

- name: Trigger All Callbacks
  meta: flush_handlers

- name: Configure | redis-server | pidfile
  lineinfile:
    state: present
    dest: /etc/redis/redis.conf
    regexp: '^#* *pidfile '
    line: "pidfile {{ redis_server_pidfile_path }}"
  notify: Reload Service | redis-server
