---
- name: Configure | redis-server | pidfile
  lineinfile:
    state: present
    dest: /etc/redis/redis.conf
    regexp: '^#* *pidfile '
    line: "pidfile {{ redis_server_pidfile_path }}"
  notify: Reload Service | redis-server
