---
- name: Reload Service | redis-server
  service:
    state: reloaded
    name: redis-server
  tags:
    - using-monit
    - disruptive

- name: Reload Service | redis-sentinel
  service:
    state: reloaded
    name: redis-sentinel
  tags:
    - using-monit
    - disruptive
